/** 以审核名单为准 · photoKind: real | ref */
const EQUIPMENT = [
  { id:'plant', name:'厂房', sources:['flow'], photo:'assets/photos/plant-building.jpg', photoKind:'ref', render:'assets/renders/plant-building.png' },
  { id:'pre-absorption', name:'预吸收塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/pre-absorption-tower.png' },
  { id:'exhaust', name:'废气排口', sources:['flow'], photo:'assets/photos/exhaust-stack.jpg', photoKind:'real', render:'assets/renders/exhaust-stack.png' },
  { id:'circulation-pump', name:'循环泵', sources:['flow'], photo:'assets/photos/circulation-pump.jpg', photoKind:'real', render:'assets/renders/circulation-pump.png' },
  { id:'condenser', name:'冷凝器', sources:['pack','flow'], photo:'assets/photos/condenser-coil.jpg', photoKind:'real', render:'assets/renders/condenser.png' },
  { id:'plate-hx', name:'板式换热器', sources:['flow'], photo:'assets/photos/plate-heat-exchanger.jpg', photoKind:'ref', render:'assets/renders/plate-heat-exchanger.png' },
  { id:'shell-tube-hx-1', name:'列管式换热器 1', sources:['flow'], photo:'assets/photos/shell-tube-hx-1.jpg', photoKind:'ref', render:'assets/renders/shell-tube-hx-1.png' },
  { id:'shell-tube-hx-2', name:'列管式换热器 2', sources:['flow'], photo:'assets/photos/shell-tube-hx-2.jpg', photoKind:'ref', render:'assets/renders/shell-tube-hx-2.png' },
  { id:'water-scrubber', name:'水洗塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/water-scrubber.png' },
  { id:'acid-scrubber', name:'酸洗塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/acid-scrubber.png' },
  { id:'crystallizer', name:'结晶釜', sources:['flow'], photo:'assets/photos/crystallizer.jpg', photoKind:'ref', render:'assets/renders/crystallizer.png' },
  { id:'fan-centrifugal', name:'离心风机', sources:['pack','flow'], photo:'assets/photos/centrifugal-fan.jpg', photoKind:'real', render:'assets/renders/fan-centrifugal.png' },
  { id:'cyclone', name:'旋风除尘器', sources:['flow'], photo:'assets/photos/cyclone-dust.jpg', photoKind:'real', render:'assets/renders/cyclone.png' },
  { id:'quench', name:'急冷塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/quench-tower.png' },
  { id:'baghouse', name:'布袋除尘器', sources:['flow'], photo:'assets/photos/baghouse.jpg', photoKind:'real', render:'assets/renders/baghouse.png' },
  { id:'desulfurization', name:'脱硫塔', sources:['flow'], photo:'assets/photos/desulfurization-tower.jpg', photoKind:'real', render:'assets/renders/desulfurization-tower.png' },
  { id:'denitrification', name:'脱硝塔', sources:['flow'], photo:'assets/photos/desulfurization-tower.jpg', photoKind:'real', render:'assets/renders/denitrification-tower.png' },
  { id:'flue-condenser', name:'烟气冷凝换热器', sources:['flow'], photo:'assets/photos/flue-gas-exchanger.jpg', photoKind:'real', render:'assets/renders/flue-gas-condenser.png' },
  { id:'biofilter', name:'生物滤池', sources:['flow'], photo:'assets/photos/biofilter.jpg', photoKind:'real', render:'assets/renders/biofilter.png' },
  { id:'induced-draft', name:'引风机', sources:['flow'], photo:'assets/photos/centrifugal-fan.jpg', photoKind:'real', render:'assets/renders/induced-draft-fan.png' },
  { id:'booster-fan', name:'增压风机', sources:['flow'], photo:'assets/photos/centrifugal-fan.jpg', photoKind:'real', render:'assets/renders/booster-fan.png' },
  { id:'squ', name:'SQU（双筒回油过滤器）', sources:['flow'], photo:'assets/photos/squ-duplex-filter.jpg', photoKind:'ref', render:'assets/renders/squ-unit.png' },
  { id:'incinerator', name:'焚烧炉', sources:['flow'], photo:'assets/photos/incinerator.jpg', photoKind:'real', render:'assets/renders/incinerator.png' },
  { id:'absorption', name:'吸收塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/absorption-tower.png' },
  { id:'alkali', name:'碱洗塔', sources:['flow'], photo:'assets/photos/alkali-scrubber.jpg', photoKind:'real', render:'assets/renders/alkali-scrubber.png' },
  { id:'wet-esp', name:'湿电除尘', sources:['flow'], photo:'assets/photos/wet-esp.jpg', photoKind:'real', render:'assets/renders/wet-esp.png' },
  { id:'carbon-adsorber', name:'活性炭吸附（水蒸气脱附）', sources:['pack','flow'], photo:'assets/photos/ref-carbon.jpg', photoKind:'ref', render:'assets/renders/carbon-adsorber.png' },
  { id:'dehydration', name:'脱水洗涤塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/dehydration-scrubber.png' }
];
