/** photoKind: real | ref | null ; sources: pack | flow */
const EQUIPMENT = [
  { id:'fan-centrifugal', name:'离心风机', sources:['pack','flow'], photo:'assets/photos/centrifugal-fan.jpg', photoKind:'real', render:'assets/renders/fan-centrifugal.png' },
  { id:'plasma', name:'等离子', sources:['pack'], photo:'assets/photos/ref-plasma.jpg', photoKind:'ref', render:'assets/renders/plasma.png' },
  { id:'photocatalytic', name:'光催化', sources:['pack'], photo:'assets/photos/photocatalytic.jpg', photoKind:'real', render:'assets/renders/photocatalytic.png' },
  { id:'condenser', name:'冷凝管 / 冷凝装置', sources:['pack','flow'], photo:'assets/photos/condenser-coil.jpg', photoKind:'real', render:'assets/renders/condenser.png' },
  { id:'electrostatic', name:'静电除油', sources:['pack'], photo:'assets/photos/electrostatic-demister.jpg', photoKind:'real', render:'assets/renders/electrostatic.png' },
  { id:'rto', name:'蓄热燃烧', sources:['pack'], photo:'assets/photos/rto-oxidizer.jpg', photoKind:'real', render:'assets/renders/rto.png' },
  { id:'carbon-adsorber', name:'活性炭吸附（水蒸气脱附）', sources:['pack','flow'], photo:'assets/photos/ref-carbon.jpg', photoKind:'ref', render:'assets/renders/carbon-adsorber.png' },
  { id:'carbon-disposable', name:'一次性活性炭吸附', sources:['pack'], photo:'assets/photos/ref-carbon.jpg', photoKind:'ref', render:'assets/renders/carbon-disposable.png' },
  { id:'wastewater', name:'污水处理站', sources:['pack'], photo:'assets/photos/wastewater-treatment.jpg', photoKind:'real', render:'assets/renders/wastewater.png' },
  { id:'vapor-recovery', name:'油气回收', sources:['pack'], photo:'assets/photos/ref-carbon.jpg', photoKind:'ref', render:'assets/renders/vapor-recovery.png' },
  { id:'loading-area', name:'物料装卸区', sources:['pack'], photo:'assets/photos/loading-area.jpg', photoKind:'real', render:'assets/renders/loading-area.png' },
  { id:'pre-absorption', name:'预吸收塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/pre-absorption-tower.png' },
  { id:'quench', name:'急冷塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/quench-tower.png' },
  { id:'absorption', name:'吸收塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/absorption-tower.png' },
  { id:'alkali', name:'碱洗塔', sources:['flow'], photo:'assets/photos/alkali-scrubber.jpg', photoKind:'real', render:'assets/renders/alkali-scrubber.png' },
  { id:'water-scrubber', name:'水洗塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/water-scrubber.png' },
  { id:'acid-scrubber', name:'酸洗塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/acid-scrubber.png' },
  { id:'sulfuric', name:'硫酸洗涤塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/sulfuric-scrubber.png' },
  { id:'dehydration', name:'脱水洗涤塔', sources:['flow'], photo:'assets/photos/alkali-scrubber.jpg', photoKind:'real', render:'assets/renders/dehydration-scrubber.png' },
  { id:'desulfurization', name:'脱硫塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/desulfurization-tower.png' },
  { id:'denitrification', name:'脱硝塔', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/denitrification-tower.png' },
  { id:'mother-liquor', name:'酸母液罐', sources:['flow'], photo:'assets/photos/scrubbing-tower.jpg', photoKind:'real', render:'assets/renders/mother-liquor-tank.png' },
  { id:'incinerator', name:'焚烧炉', sources:['flow'], photo:'assets/photos/incinerator.jpg', photoKind:'real', render:'assets/renders/incinerator.png' },
  { id:'wet-esp', name:'湿电除尘', sources:['flow'], photo:'assets/photos/wet-esp.jpg', photoKind:'real', render:'assets/renders/wet-esp.png' },
  { id:'flue-condenser', name:'烟气冷凝换热器', sources:['flow'], photo:'assets/photos/condenser-coil.jpg', photoKind:'real', render:'assets/renders/flue-gas-condenser.png' },
  { id:'biofilter', name:'生物滤池', sources:['flow'], photo:'assets/photos/biofilter.jpg', photoKind:'real', render:'assets/renders/biofilter.png' },
  { id:'cyclone', name:'旋风除尘器', sources:['flow'], photo:'assets/photos/cyclone-dust.jpg', photoKind:'real', render:'assets/renders/cyclone.png' },
  { id:'baghouse', name:'布袋除尘器', sources:['flow'], photo:'assets/photos/baghouse.jpg', photoKind:'real', render:'assets/renders/baghouse.png' },
  { id:'waste-heat-boiler', name:'余热锅炉', sources:['flow'], photo:'assets/photos/rto-oxidizer.jpg', photoKind:'ref', render:'assets/renders/waste-heat-boiler.png' },
  { id:'circulation-pump', name:'循环泵', sources:['flow'], photo:'assets/photos/circulation-pump.jpg', photoKind:'real', render:'assets/renders/circulation-pump.png' },
  { id:'spray-pump', name:'喷淋泵', sources:['flow'], photo:'assets/photos/circulation-pump.jpg', photoKind:'real', render:'assets/renders/spray-pump.png' },
  { id:'induced-draft', name:'引风机', sources:['flow'], photo:'assets/photos/centrifugal-fan.jpg', photoKind:'real', render:'assets/renders/induced-draft-fan.png' },
  { id:'booster-fan', name:'增压风机', sources:['flow'], photo:'assets/photos/centrifugal-fan.jpg', photoKind:'real', render:'assets/renders/booster-fan.png' },
  { id:'squ', name:'SQU', sources:['flow'], photo:'assets/photos/ref-plasma.jpg', photoKind:'ref', render:'assets/renders/squ-unit.png' },
  { id:'exhaust', name:'废气排口', sources:['flow'], photo:'assets/photos/exhaust-stack.jpg', photoKind:'real', render:'assets/renders/exhaust-stack.png' }
];
